### ISSUE TITLE
Mocking a module's function ignores the last params when matching expectation

### ISSUE THREAD

**Issue by lindycoder** [has207/flexmock#111]
When mocking a module's function, the last parameter is ignored.  According to the my research the _normalize_named_args method will do this if

```python
if inspect.ismethod(getattr(self._mock, self.name)):
      args = argspec.args[1:]
    else:
      args = argspec.args
```

So it seems to assume the first parameter is "self" and on a module function it is not, maybe i don't have the right way to mock a module function, if so i'm sorry, please correct me.

If not, here's the steps to reproduce

```python
import unittest
from flexmock import flexmock
import sys

def my_method(my_arg, my_kwarg=None):
    return 1

class MyTest(unittest.TestCase):
    def test_it(self):

        flexmock(sys.modules[__name__])\
            .should_receive("my_method")\
            .with_args("expected", my_kwarg="whatever")\
            .and_return("a_value")

        result = my_method("expected", my_kwarg="blah blah blah")
        self.assertEqual(result, "a_value")
```

Here calling my_method with "blah blah blah" should be failing with a MethodSignatureError

Thank you very much

Martin

**Comment by has207** [comment]
Make sure you test against latest flexmock on github, I can't reproduce locally.

**Comment by lindycoder** [comment]
I did, i wrote a test to show you, it's on this branch

https://github.com/lindycoder/flexmock/tree/last_kwarg_ignored

**Comment by bkabrda** [comment]
With latest upstream, the test *doesn't* reproduce the issue for me neither on Python 2.7 nor on Python 3.4 (`FlexmockError` is not raised).
@lindycoder are you sure you don't have an older version flexmock installed somewhere on your `sys.path` that would get loaded before the `flexmock.py` from the checked git repo? If not, could you provide some details on your environment - like Python interpreter version(s) you can reproduce this on, OS you're running, `sys.path`.

**Comment by lindycoder** [comment]
With the upstream

And i recall that the error IS that FlexmockError is NOT raised.  My fork shows a broken test that i did not fix

```
:~/work/flexmock$ virtualenv venv
New python executable in venv/bin/python
Installing setuptools, pip, wheel...done.

:~/work/flexmock$ source venv/bin/activate

(venv):~/work/flexmock$ python --version
Python 2.7.6

(venv):~/work/flexmock$ cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=14.04
DISTRIB_CODENAME=trusty
DISTRIB_DESCRIPTION="Ubuntu 14.04.3 LTS"

(venv):~/work/flexmock$ tests/run_tests.sh 
python2.4 NOT FOUND
nosetests-2.4 NOT FOUND
py.test NOT FOUND
trial-2.4 or trial2.4 NOT FOUND
python2.5 NOT FOUND
nosetests-2.5 NOT FOUND
py.test NOT FOUND
trial-2.5 or trial2.5 NOT FOUND
python2.6 NOT FOUND
nosetests-2.6 NOT FOUND
py.test NOT FOUND
trial-2.6 or trial2.6 NOT FOUND
python2.7
...........................................................................................................................E............................................
======================================================================
ERROR: test_module_level_function_with_kwargs (flexmock_test.TestFlexmockUnittest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "flexmock/tests/flexmock_test.py", line 908, in test_module_level_function_with_kwargs
    assertRaises(FlexmockError, module_level_function, 1, args="not expected")
  File "flexmock/tests/flexmock_test.py", line 49, in assertRaises
    raise Exception('%s not raised' % exception.__name__)
Exception: FlexmockError not raised

----------------------------------------------------------------------
Ran 167 tests in 0.030s

FAILED (errors=1)
nosetests with python2.7
nose not installed for python2.7
py.test NOT FOUND
trial-2.7 or trial2.7 NOT FOUND
python3.1 NOT FOUND
nosetests-3.1 NOT FOUND
py.test NOT FOUND
trial-3.1 or trial3.1 NOT FOUND
python3.2 NOT FOUND
nosetests-3.2 NOT FOUND
py.test NOT FOUND
trial-3.2 or trial3.2 NOT FOUND
python3.3 NOT FOUND
nosetests-3.3 NOT FOUND
py.test NOT FOUND
trial-3.3 or trial3.3 NOT FOUND
python3.4
...........................................................................................................................E...............................................
======================================================================
ERROR: test_module_level_function_with_kwargs (flexmock_test.TestFlexmockUnittest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/flexmock/tests/flexmock_test.py", line 908, in test_module_level_function_with_kwargs
    assertRaises(FlexmockError, module_level_function, 1, args="not expected")
  File "/flexmock/tests/flexmock_test.py", line 49, in assertRaises
    raise Exception('%s not raised' % exception.__name__)
Exception: FlexmockError not raised

----------------------------------------------------------------------
Ran 170 tests in 0.050s

FAILED (errors=1)
nosetests-3.4 NOT FOUND
py.test NOT FOUND
trial-3.4 or trial3.4 NOT FOUND
python3.5 NOT FOUND
nosetests-3.5 NOT FOUND
py.test NOT FOUND
trial-3.5 or trial3.5 NOT FOUND
cpython NOT FOUND
pypy NOT FOUND
jython NOT FOUND
```

**Comment by bkabrda** [comment]
Ah, I see now that I've misread your test. So yeah, I can reproduce the issue, I'll try digging into that.

**Comment by bkabrda** [comment]
I think I got it. The problem is that the `_normalized_named_args` uses `inspect.ismethod` on `getattr(self._mock, self.name)`, which is the mock, not the original - and the mock is always a method (`mock_method`).
So I think the proper way to fix this is to use `inspect.ismethod(self.original)` - all tests (even the ones provided for this bug) pass with this change. @lindycoder would be ok with you if I sent a pull request containing tests you wrote?

**Comment by lindycoder** [comment]
Absolutely :) Thank you very much for looking into it
